version: "3.8"

services:
  gbans:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - dl_cache:/app/.cache
      - ./config.yml:/app/config.yml
    depends_on:
      - postgres
    networks:
      - test_network
    environment:
      UT_DATABASE_DSN: postgresql://uncletopia-web:uncletopia-web@uncletopia-web:5433/uncletopia-web
      UT_GENERAL_STEAM_KEY: ${GBANS_GENERAL_STEAM_KEY}
    command: make test
  postgres:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: uncletopia-web
      POSTGRES_DB: uncletopia-web
      POSTGRES_PASSWORD: uncletopia-web
    networks:
      - test_network

volumes:
  dl_cache:

networks:
  test_network: